#!/bin/bash
curl http://localhost/perrir.php > /var/www/perrir.html
curl http://localhost/maps.php > /var/www/maps.html
curl http://localhost/trends.php > /var/www/trends.html
curl http://localhost/global.php > /var/www/global.html
curl http://localhost/top10.php > /var/www/top10.html
curl http://localhost/perrir.php?rir=afrinic > /var/www/afrinic.html
curl http://localhost/perrir.php?rir=apnic > /var/www/apnic.html
curl http://localhost/perrir.php?rir=arin > /var/www/arin.html
curl http://localhost/perrir.php?rir=lacnic > /var/www/lacnic.html
curl http://localhost/perrir.php?rir=ripe > /var/www/ripe.html
curl http://localhost/validitytables.php > /var/www/validitytables.html
curl http://localhost/validitytables.php?v=V > /var/www/validitytables_V.html
curl http://localhost/validitytables.php?v=I% > /var/www/validitytables_I.html
curl http://localhost/validitytables.php?v=IA > /var/www/validitytables_IA.html
curl http://localhost/validitytables.php?v=IP > /var/www/validitytables_IP.html
curl http://localhost/validitytables.php?v=IQ > /var/www/validitytables_IQ.html
curl http://localhost/validitytables.php?v=IB > /var/www/validitytables_IB.html
curl http://localhost/ipcomp.php > /var/www/ipcomp.html
curl http://localhost/index.php > /var/www/index.html
